name: Go ğŸ¹

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Golang Makefile Build ğŸ“œ
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      working-directory: golang
      run: make build

    - name: Test
      working-directory: golang
      run: make test
